trigger:
  branches:
    include:
      - main
      - dev
      - qa

variables:
  # Fix to extract only the branch name from 'refs/heads/dev'
  - template: variables/vars-$(Build.SourceBranchName | split('/')[2]).yml
  - group: MySecretVariableGroup

stages:
  - stage: Debug
    jobs:
      - job: CheckFiles
        steps:
          - script: echo "Branch Name:$(Build.SourceBranchName)"
          - script: echo "Resolved YAML Path:variables/vars-$(Build.SourceBranchName | split('/')[2]).yml"
          - script: ls -R variables  # Check if the 'variables' folder exists
          - script: cat variables/vars-$(Build.SourceBranchName | split('/')[2]).yml  # Read the expected file

  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Environment:$(REACT_APP_RAPID_API)"
          - script: echo "App URL:$(appUrl)"
          - script: echo "Will not display secrets, but can use them securely."
