trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - checkout: self

  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'CTG-DevOps-Org'
      projectKey: 'ctg-devops-org'
      scannerMode: 'CLI'
      extraProperties: |
        sonar.projectName=Youtube-clone-Vaibhavwa
        sonar.projectVersion=1.0
        sonar.sources=.

  - task: SonarCloudAnalyze@1

  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
