trigger:
  branches:
    include:
      - main
      - dev
      - qa

variables:
  - template: variables/vars-$(Build.SourceBranchName).yml
  - group: MySecretVariableGroup

stages:
  - stage: Build
    jobs:
      - job: BuildJob
        steps:
          - script: echo "Environment: $(environmentName)"
          - script: echo "App URL: $(techtutorialswithvaibhav-gve9e7cdfvd5evcb.centralindia-01.azurewebsites.net)"
          - script: echo "Will not display secrets, but can use them securely."